/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Gradle build and Git workflow successful.";
    }

    public static void main(String[] args) {
        System.out.println("Gradle build message updated by Student B.");
    }
}
